name = "heptasean/aiken-trivial"
version = "1.0.0"
compiler = "v1.0.29-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "The most trivial validators: always_succeed and always_fail"

[repository]
user = "heptasean"
project = "aiken-trivial"
platform = "github"
